import matplotlib.pyplot as plt
import numpy as np

def show_graphs(x1, y1, x2, y2_1, y2_2, x1_label, y1_label, x2_label, y2_label, y1_name, y2_1_name, y2_2_name, title1, title2):
    _, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    ax1.plot(x1, y1, label=y1_name)
    ax2.plot(x2, y2_1, label=y2_1_name)
    ax2.plot(x2, y2_2, label=y2_2_name)
    ax1.set_xlabel(x1_label)
    ax1.set_ylabel(y1_label)
    ax1.set_xlim(0, None)
    ax1.set_ylim(0, None)
    ax1.set_title(title1)
    ax1.legend()
    ax2.set_xlabel(x2_label)
    ax2.set_ylabel(y2_label)
    ax2.set_xlim(0, None)
    ax2.set_ylim(0, None)
    ax2.set_title(title2)
    ax2.legend()
    plt.pause(.0001)
    plt.close()

def show_results(x1, y1, x2, y2_1, y2_2, x1_label, y1_label, x2_label, y2_label, y1_name, y2_1_name, y2_2_name, title1, title2):
    _, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    ax1.plot(x1, y1, label=y1_name)
    ax2.plot(x2, y2_1, label=y2_1_name)
    ax2.plot(x2, y2_2, label=y2_2_name)
    ax1.set_xlabel(x1_label)
    ax1.set_ylabel(y1_label)
    ax1.set_xlim(0, None)
    ax1.set_ylim(0, None)
    ax1.set_title(title1)
    ax1.legend()
    ax2.set_xlabel(x2_label)
    ax2.set_ylabel(y2_label)
    ax2.set_xlim(0, None)
    ax2.set_ylim(0, None)
    ax2.set_title(title2)
    ax2.legend()
    plt.show()
